document.writeln("<style type=\'text/css\'>");
document.writeln(".style3 {");
document.writeln("	text-align: center;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("<div class=\'style3\'>");
document.writeln("<img src=\'http://owvnkcgpj.bkt.clouddn.com/timg.jpg\'  /><br />");
document.writeln("	免费下载：扫描二维码关注猜微信【xiaodiu818】<br>");
document.writeln("</div>");
document.writeln("<table style=\'width: 100%\' align=\'center\'>");
document.writeln("	<tr>");
document.writeln("		<td class=\'style2\' style=\'width: 119px\'>1、回复 “139”</td>");
document.writeln("		<td class=\'style2\'>免费领取《AutoCAD2004~2017 for win/mac+天正建筑》</td>");
document.writeln("	</tr>");
document.writeln("	<tr>");
document.writeln("		<td class=\'style2\' style=\'width: 119px\'>2、回复 “480”</td>");
document.writeln("		<td class=\'style2\'>免费领取《PS CS6 Win+mac》</td>");
document.writeln("	</tr>");
document.writeln("	<tr>");
document.writeln("		<td class=\'style2\' style=\'width: 119px\'>3、回复 “1101”</td>");
document.writeln("		<td class=\'style2\'>免费领取《Adobe cc2015全系列 Win+mac》</td>");
document.writeln("	</tr>");
document.writeln("	<tr>");
document.writeln("		<td class=\'style2\' style=\'width: 119px\'>4、回复 “759”</td>");
document.writeln("		<td class=\'style2\'>免费领取《Adobe cc2017全系列》</td>");
document.writeln("	</tr>");
document.writeln("	<tr>");
document.writeln("		<td class=\'style2\' style=\'width: 119px\'>5、回复 “578”</td>");
document.writeln("		<td class=\'style2\'>免费领取《key shot5.1/6.0 for Win+mac》</td>");
document.writeln("	</tr>");
document.writeln("	<tr>");
document.writeln("		<td class=\'style2\' style=\'width: 119px\'>6、回复 “222”</td>");
document.writeln("		<td class=\'style2\'>免费领取《草图大师 8.0/2013-2017 forWin+mac |+V-Ray》</td>");
document.writeln("	</tr>");
document.writeln("	<tr>");
document.writeln("		<td class=\'style2\' style=\'width: 119px\'>7、回复 “501”</td>");
document.writeln("		<td class=\'style2\'>免费领取《OFFIC2003-2016 for Win+mac》</td>");
document.writeln("	</tr>");
document.writeln("	<tr>");
document.writeln("		<td class=\'style2\' style=\'width: 119px\'>8、回复 “590”</td>");
document.writeln("		<td class=\'style2\'>免费领取《犀牛Rhino5.0/4.0+Vr》</td>");
document.writeln("	</tr>");
document.writeln("	<tr>");
document.writeln("		<td class=\'style2\' style=\'width: 119px\'>9、回复 “1356”</td>");
document.writeln("		<td class=\'style2\'>免费领取《3Dmax 32/64位软件》</td>");
document.writeln("	</tr>");
document.writeln("	<tr>");
document.writeln("		<td class=\'style2\' style=\'width: 119px\'>10、回复 “590”</td>");
document.writeln("		<td class=\'style2\'>免费领取《Maya软件2013-2017》</td>");
document.writeln("	</tr>");
document.writeln("	<tr>");
document.writeln("		<td class=\'style2\' style=\'width: 119px\'>11、回复 “590”</td>");
document.writeln("		<td class=\'style2\'>免费领取《SW SolidWorks2017/2016/2015/2014软件》</td>");
document.writeln("	</tr>");
document.writeln("	<tr>");
document.writeln("		<td class=\'style2\' style=\'width: 119px\'>12、回复 “590”</td>");
document.writeln("		<td class=\'style2\'>免费领取《Revit 2017/2016/2015/ BIM软件》</td>");
document.writeln("	</tr>");
document.writeln("</table>");
document.writeln("");